In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [2]:
randint = torch.randint(-100, 100, (6,))
print(randint)

tensor([  8, -70, -40,  94, -60, -37])


In [3]:
tensor = torch.tensor([[1,0],[2.5,1.2],[4.5,9.9]])
tensor

tensor([[1.0000, 0.0000],
        [2.5000, 1.2000],
        [4.5000, 9.9000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
probabilities = torch.tensor([0.1, 0.9])
# 10% -> 0 and 90% -> 1
# generate 10 samples
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [13]:
tensor = torch.tensor([1,2,3,4])
# concatenating two tensors together ([1,2,3,4] and [5])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [14]:
# triangle lower
# This is useful because the 0s are like the future answers that we are trying to predict. We can't know them beforehand.
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [15]:
# triangle upper
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [16]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [17]:
# apply each element x in the tensor to 2.71^x
out = torch.exp(out)
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
input = torch.zeros(2,3,4)
# Swapping the 0th and the 2nd dimensions
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [19]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
# Linear transformation
# This is important because the number of neurons between each layer is different. This allows transformation of tensor into other shapes so they
# can be processed by the next layer.
# For eaxmple, nn.Linear(3,5) takes a tensor of size 3, multiply it by a weight matrix of size (5, 3), producing a tensor of size 5. This allows
# the model to learn relationships between features. The weight matrix is initialized to random values but eventually converges to a fixed value.
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))

tensor([ 8.3115, -3.9082,  7.5245], grad_fn=<SqueezeBackward4>)


In [21]:
import torch.nn.functional as F

tensor = torch.tensor([1.,2.,3.])
# Applying the softmax function on the tensor
# The softmax function exponentiates each element x in the tensor to 2.71^x and divides each of them by the exponentiated total sum.
softmax_output = F.softmax(tensor, dim = 0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [22]:
# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_outputs = embedding(input_indices)

# The output will be a tensor of shape (4, 100) where 4 is the number of input indices and 100 is the dimension of the embedding vector
# Embedding is required to transform tokens into a numerical representation that somehow carries their semantics (so into vectors).
print(embedded_outputs.shape)

torch.Size([4, 100])


In [23]:
a = torch.Tensor([[1,2], [3,4], [5,6]])
b = torch.Tensor([[7,8,9], [10, 11, 12]])
# dot product between matrices
# The size of the two matrices must be a * b and b * c, and the resulting matrix will have size a * c.
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [24]:
int_64 = torch.randint(1, (3,2))

float_32 = torch.rand(2,3)

print(int_64.dtype, float_32.dtype)
# The following code produce an error because these two matrices have different data types. This can be fixed by casting one of them to 
# the dtype of the other
# eg.int_64 = int_64.float()
print(int_64 @ float_32)

torch.int64 torch.float32


RuntimeError: expected m1 and m2 to have the same dtype, but got: __int64 != float

In [36]:
# The following are some common activation functions.
# When forward training the model, use the function from torch.nn not from F.
x = torch.tensor([-0.05], dtype=torch.float32)
# ReLU function returns 0 if the input is < 0, and returns input itself otherwise
y = F.relu(x)
print(y)
# Sigmoid function returns 1/(1+exp(-x))
# Output ranges from 0 to 1
y = F.sigmoid(x)
print(y)
# Tanh function returns (exp(x)-exp(-x))/(exp(x)+exp(-x))
# Output ranges from -1 to 1
y = F.tanh(x)
print(y)

x = torch.tensor([0.05], dtype=torch.float32)
y = F.relu(x)
print(y)
y = F.sigmoid(x)
print(y)
y = F.tanh(x)
print(y)

tensor([0.])
tensor([0.4875])
tensor([-0.0500])
tensor([0.0500])
tensor([0.5125])
tensor([0.0500])
